version: "3.9.1"
services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama_service
    ports:
      - "11434:11434"
    command: ["serve"]
    environment:
      - MODEL=llama3.2
    volumes:
      - ./ollama_data:/root/.ollama

  python_app:
    build:
      context: ./python_app
      dockerfile: Dockerfile
    container_name: python_service
    depends_on:
      - ollama
    links:
      - ollama
    volumes:
      - ./python_app:/app
    ports:
      - "6789:6789"
    command: ["uvicorn", "rag_qa:app", "--host", "0.0.0.0", "--port", "6789"]
